BraneFramework/brane

brane-ctl/build.rs
The env vars were only set if the files were downloaded, but the `continue` would skip setting the variables if the path already exists and thus the build would fail after the first build.
=> Set cfssl env vars if path exist

brane-cli/src/instance.rs
Brane instance edit would create a path with the filename repeated. Now it doesn't
=> fix(cli): Remove doubly appended filename in path

make.py
In the list of targets there targets ending in `-image-build` which do not actually exist. I renamed them to the `-image` targets so they match with the existing target. I am unfamiliar with `make.py` and it is complicated to graps at times, so it would be nice if this was checked.
Additionally, we should now print a friendly error when somebody tries to make a non-existent target instead of failing inside the dep tree.
=> User friendly error and fix image build target names.

Cargo.lock, brane-api/Cargo.toml, brane-cfg/Cargo.toml, brane-cli/Cargo.toml, brane-ctl/Cargo.toml, brane-job/Cargo.toml, brane-let/Cargo.toml, brane-oas/Cargo.toml, brane-reg/Cargo.toml, brane-tsk/Cargo.toml, specifications/Cargo.toml
Old deps are no longer maintained. Swapping them still compiles.
Fixes: #72
=> chore: Move to yaml_rust2 and serde_yml

brane-tsk/Cargo.toml
Example does not seem to exist. Lets remove it for now, if somebody wants to add it again that is fine, but this breaks stuff, right now.
=> fix(tsk): Remove non-existent example

Cargo.lock, brane-api/Cargo.toml, brane-ast/Cargo.toml, brane-cc/Cargo.toml, brane-cfg/Cargo.toml, brane-cli-c/Cargo.toml, brane-cli/Cargo.toml, brane-ctl/Cargo.toml, brane-drv/Cargo.toml, brane-dsl/Cargo.toml, brane-exe/Cargo.toml, brane-job/Cargo.toml, brane-let/Cargo.toml, brane-log/Cargo.toml, brane-oas/Cargo.toml, brane-plr/Cargo.toml, brane-prx/Cargo.toml, brane-reg/Cargo.toml, brane-shr/Cargo.toml, brane-tsk/Cargo.toml, specifications/Cargo.toml
Minimal versions were almost universally set incorrectly. This was a huge endeavour to fix, however I tried to be diligent about it. It will be the case that some are set too high now, but too high is a lot better than the previous too low.
This only takes take of direct minimal versions. Preferably we would also ensure that the transient dependencies have the correct minimal versions, but this will suffice (for now).
I can only fully test this when #90 has been merged, as some builds fail on the base of this branch.
=> chore: Update Cargo minimal versions

brane-ctl/src/download.rs, brane-ctl/src/errors.rs, make.py
My backups have quadrupled in size, because if you download an image using `branectl` before you ever compile anything in brane, cargo will never annotate its target directory with a `CACHEDIR.TAG` (and rightfully so). However, this does mean that most backup solutions will gladly backup all your nice debug builds. :smiling_face_with_tear:.
Lets fix that, we do add a cachetag to the download directory itself if the target directory is not the one usually used by cargo.
=> fix(ctl): Add CACHEDIR.TAG to target dir on create

.github/dependabot.yml
Unfortunately, as of now, it is impossible to validate dependabot configurations beforehand, I checked it twice, but there might be something I missed. Right now, the limit for open dependabot pull requests for version updates is set to five at a time. This might be a little on the low end for a project of this size, but we shall see.
=> chore(deps): Add dependabot

brane-ctl/build.rs
It would check if the source existed and if so not compile the binary. This has been changed to checking for the existence of the binary itself. With this change our mac-os builds on ARM should not be failing anymore, which is one of the last blocking issues for #100
=> fix(ctl): Correctly compile CFSSL on ARM arch

CHANGELOG.md, brane-cli/src/main.rs
Created two subcommands: package and workflow.
The following subcommands were moved under the package subcommand:
build, import, inspect, list, load, pull, push, remove, test, search, unpublish
The following subcommands were moved under the workflow subcommand:
check, repl, run
Code has only been checked with the compiler and inspected with the help info.
This has the added benefit of adding a noun to each command which makes everything sound way more sensible. E.g. `brane package push` 
closes: #80
=> refactor(cli)!: Restructure command interface

Cargo.lock, brane-ast/Cargo.toml, brane-cfg/Cargo.toml, brane-cli/Cargo.toml, brane-dsl/Cargo.toml, brane-exe/Cargo.toml, brane-job/Cargo.toml, brane-let/Cargo.toml, brane-reg/Cargo.toml, brane-shr/Cargo.toml, brane-tsk/Cargo.toml, specifications/Cargo.toml
This has been checked by compilation with cargo-udeps as source
@lut99 Could you scan this through for something I could have missed here?
=> chore(deps): Remove seamingly unused dependencies

docker-compose-central.yml, docker-compose-proxy.yml, docker-compose-worker.yml
Add alias for host.docker.internal
This change makes setting up Brane on single machines a lot easier
Note that we cannot use host-gateway instead. This is a special string that can be used in extra hosts, that will be _substituted_ by the docker host IP address, it is not a DNS entry itself.
=> feat(docker): Add host.docker.internal

Dockerfile.rls, make.py
Fixed #117
A recent change over at the policy reasoner has introduced multiple binaries for multiple reasoning backends. The Dockerfile for the checker image hasn't been updated, so it attempted to copy the no-longer existing `policy-reasoner`.
In addition, also added a `make.py` flag for changing the reasoner binary that is being built.
=> Fix checker image not compiling

brane-ctl/src/cli.rs, brane-ctl/src/lifetime.rs, brane-ctl/src/main.rs, brane-ctl/src/spec.rs
With this subcommand you can see the collective logs of an entire node in a single output.
Fixes: #112
=> feat(branectl): Add logs subcommand

brane-ctl/src/upgrade.rs, brane-ctl/src/wizard.rs, brane-ctl/src/wizard/validator.rs, brane-shr/src/input.rs
Also add some already used variants of a couple of validators
Edit: as it is shares the same scope, I also added a `input_vec` function. This is basically the `input_map` function, but without any keys.
=> feat: Add validator for input functions

brane-cli/Cargo.toml, brane-ctl/Cargo.toml
Without this, you have to type `--bin brane` or `--bin branectl` every time.
=> chore(cargo): Set default run for packages with multiple binaries

make.py
Due to an error the maker was broken and could not actually build targets anymore.
I would swear I not only tested this, but used to run this as my default branch for a bit.
Anyway, this should fix it
=> fix(make): Replace list with dict in BuilderTarget src_deps

CHANGELOG.md, brane-cfg/src/node.rs, brane-job/src/worker.rs, make.py
This is the yield of a simple grep, I might be missing some instances, but this should be most.
I left some old stuff regarding k8s as I was unclear whether it was refering to Brane or k8s control planes, but that stuff is unused right now anyway.
=> style: Rename control node to central node

.github/dependabot.yml
This should in theory group together all the policy reasoner updates, as they should be updated in tandem.
I don't really have a way to check if this is going to work, nor do I have the access to see if it did afterwards.
@lut99, Could you check if this makes sense?
The documentation on this particular setting can be found here:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#example-1
After merging, you can see in the same panel where you enabled it if the file is properly parsed.
=> chore(dependabot): Group together policy reasoner updates

.github/workflows/ci.yml, .github/workflows/mixin-cargo-check.yml, .github/workflows/mixin-cargo-test.yml
GitHub seems to keep switching back and forth between 22.04 and 24.04 on `-latest`.
Fixes: #178
=> chore(ci): Fix linux runners to ubuntu 24.04

.github/workflows/docs.yml
Currently this will redirect the root to the unstable (main)
documentation. Once we do another stable release; I suggest we add an
compiled artifact with the docs, so we can download and publish those as
well.
You can preview them at:
https://danielvoogsgerd.github.io/brane/
=> chore(ci): Publish documentation on GitHub pages

.github/workflows/ci.yml, .github/workflows/nightly.yml
This can be used less stringently than the normal CI checks as it is not
actually our toolchain that encounters these problems
=> chore(ci): Move nightly CI to separate workflow

.github/workflows/ci.yml, .github/workflows/mixin-cargo-check.yml, .github/workflows/mixin-cargo-clippy.yml, .github/workflows/mixin-cargo-llvm-cov.yml, .github/workflows/mixin-cargo-test.yml, .github/workflows/nightly.yml, rust-toolchain.toml
Inspired by this blogpost (https://swatinem.de/blog/rust-toolchain/) 
we are setting our rust toolchain and will
start managing it as a dependency. This will make compiling more easy in
case this project is ever shelved. Additionally, once used in CI it will
ensure that CI should not randomly break when new clippy checks land in
the latest rust version for example.
=> chore(rust): Set default toolchain

.github/workflows/ci.yml, .github/workflows/mixin-cargo-check.yml, .github/workflows/mixin-cargo-clippy.yml, .github/workflows/mixin-cargo-llvm-cov.yml, .github/workflows/mixin-cargo-test.yml
By caching dependencies, we might be able to speed up our CI
Very non-scientific measurement decreased CI times from 25 minutes to 6 minutes, more often it should lie somewhere in between, but this seems promising.
=> chore(deps): Enable rust cache

CHANGELOG.md, Cargo.lock, Cargo.toml, Dockerfile.dev, Dockerfile.rls, brane-cli/src/build_common.rs, brane-ctl/Cargo.toml, brane-ctl/src/cli.rs, brane-ctl/src/download.rs, brane-ctl/src/generate.rs, brane-job/Cargo.toml, brane-job/src/worker.rs, brane-prx/Cargo.toml, brane-reg/Cargo.toml, brane-reg/src/data.rs, tests/packages/copy_result/container.yml
This does not fork eflint-server-go yet
Also a mention of EPIF-Configurations remains on the epi-project organisation
=> chore: Rename epi-project to braneframework

brane-cfg/Cargo.toml, brane-dsl/Cargo.toml, brane-job/Cargo.toml, brane-let/Cargo.toml, brane-log/Cargo.toml, specifications/Cargo.toml
In case anybody is wondering. At time of writing 2024 is out, but this
would be a bad idea as it would increase our MSRV to 1.85. Limiting
ourselves to one single rust version for support.
=> chore(rust): Bump rust edition to 2021

.github/workflows/ci.yml, .github/workflows/mixin-cargo-build.yml, .github/workflows/mixin-cargo-check.yml, .github/workflows/mixin-cargo-clippy.yml, .github/workflows/mixin-cargo-test.yml, brane-ast/src/errors.rs, brane-exe/src/pc.rs, specifications/src/profiling.rs
From the documentation:
> Any environment variables set in an env context defined at the workflow
> level in the caller workflow are not propagated to the called workflow.
> For more information, see Store information in variables and Accessing
> contextual information about workflow runs.
=> Fixing more CI problems

brane-api/src/cli.rs, brane-api/src/main.rs, brane-cc/src/cli.rs, brane-cc/src/main.rs, brane-cli/src/main.rs, brane-ctl/src/cli.rs, brane-ctl/src/completions.rs, brane-ctl/src/main.rs, brane-drv/src/cli.rs, brane-drv/src/main.rs, brane-job/src/cli.rs, brane-job/src/main.rs, brane-let/src/cli.rs, brane-let/src/main.rs, brane-plr/src/cli.rs, brane-plr/src/main.rs, brane-prx/src/cli.rs, brane-prx/src/main.rs, brane-reg/src/cli.rs, brane-reg/src/main.rs
All command line arguments are now defined in a separate module called
cli and the main parser is called `Cli`. This helps a lot with external
imports of these modules, i.e. xtasks in our case.
=> refactor: Restructure all cli interfaces

.github/workflows/ci.yml, brane-cli-c/src/lib.rs
This does not work on arm because there c_chars are u8's
See: https://github.com/rust-lang/rust/blob/10a76d634781180b4f5402c519f0c237d3be6ee6/library/core/src/ffi/primitives.rs#L37
=> fix(cli-c): Use c_char for c chars instead of platform specific i8

Cargo.lock, Cargo.toml, brane-api/Cargo.toml, brane-cli/Cargo.toml, brane-ctl/Cargo.toml, brane-drv/Cargo.toml, brane-job/Cargo.toml, brane-plr/Cargo.toml, brane-prx/Cargo.toml, brane-reg/Cargo.toml, brane-shr/Cargo.toml, brane-tsk/Cargo.toml, specifications/Cargo.toml
Setting reqwest as workspace dependency.
Also disable a root store by default. Every crate now as to enable it
themselves in order to use it.
This is going to need some back and forth for this to propagate through
our circular dependency.
=> chore(deps): Replace openssl with rustls
