BraneFramework/brane

CHANGELOG.md, brane-job/Cargo.toml, brane-job/src/errors.rs
Added small fixes that _should_ have been in previous pull request :#
=> Small fixes before 0.6.1 release

make.sh
=> Fixed Github download links not working

CHANGELOG.md, Dockerfile.dev, Dockerfile.rls, brane-cli/src/vm.rs, brane-ctl/src/lifetime.rs, brane-ctl/src/main.rs, brane-drv/src/handler.rs, brane-drv/src/planner.rs, brane-drv/src/vm.rs, brane-exe/src/dummy.rs, brane-exe/src/errors.rs, brane-exe/src/spec.rs, brane-exe/src/thread.rs, brane-exe/src/vm.rs, brane-job/src/worker.rs, brane-plr/src/planner.rs, brane-reg/src/data.rs, specifications/Cargo.toml, specifications/src/profiling.rs, specifications/src/profiling_old.rs
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
* **What is the current behavior?** (You can also link to an open issue here)
* **What is the new behavior (if this is a feature change)?**
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
* **Other information**:
=> Profiling again

Cargo.toml
Oop changing the version number is important...
=> Bump to 2.0.0

brane-cli/src/build_common.rs
Small but important fix for the tutorial
=> Fixed wrong branelet architecture being used

CHANGELOG.md, Cargo.lock, Cargo.toml, Dockerfile.mac, brane-cc/Cargo.toml, brane-cli-c/Cargo.toml, brane-cli/Cargo.toml, brane-cli/src/errors.rs, brane-cli/src/main.rs, brane-ctl/Cargo.toml, brane-shr/src/fs.rs, src/main.rs
Or rather, removed git2 and changed a few subtle settings to make everything compile in Zig. The _real_ make.py compatability has yet to come...
=> Adding cross-compilation functionality

brane-shr/src/utilities.rs
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
* **What is the current behavior?** (You can also link to an open issue here)
* **What is the new behavior (if this is a feature change)?**
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
* **Other information**:
=> Also added path-dependent variants of `test_on_dsl_files`

examples/arithmetic/bash/container.yml, examples/arithmetic/nodejs/container.yml, examples/arithmetic/python/container.yml, examples/help/container.yml, examples/tutorial/6/container.yml, examples/wordcount/base64/container.yml, examples/wordcount/wordcloud/container.yml
Several example packages were broken for internal and external reasons. These have been resolved.
=> Fix several example packages

specifications/Cargo.toml
=> fix(spec): Add rc flag to serde

brane-api/Cargo.toml, brane-ast/Cargo.toml, brane-cc/Cargo.toml, brane-cfg/Cargo.toml, brane-cli-c/Cargo.toml, brane-cli/Cargo.toml, brane-ctl/Cargo.toml, brane-drv/Cargo.toml, brane-dsl/Cargo.toml, brane-exe/Cargo.toml, brane-job/Cargo.toml, brane-let/Cargo.toml, brane-log/Cargo.toml, brane-oas/Cargo.toml, brane-plr/Cargo.toml, brane-prx/Cargo.toml, brane-reg/Cargo.toml, brane-shr/Cargo.toml, brane-tsk/Cargo.toml, overview/Cargo.toml, specifications/Cargo.toml
Settings MSRV for all workspace members. 3 workspace members are still missing because of: #85
=> chore(msrv): Set MSRV versions in workspace member

Cargo.lock, brane-api/Cargo.toml, brane-cli/Cargo.toml, brane-job/Cargo.toml, brane-tsk/Cargo.toml, specifications/Cargo.toml
Policy reasoner bumped their minimal version of chrono, so we have to as well.
=> chore(deps): Bump minimal chrono version

Cargo.lock, brane-cli/Cargo.toml, brane-cli/src/data.rs, brane-cli/src/errors.rs, brane-shr/Cargo.toml, brane-shr/src/input.rs
Because this is the leading non-zero number this is a major version bump, but most of all, this crate existed in the workspace in two different major versions.
=> chore(deps): Bump dialoguer crate to version 0.11

.github/workflows/mixin-cargo-check.yml
=> fix(ci): Check all features using cargo hack

.github/workflows/audit.yml
The old version was broken. I replaced it with modern replacements
=> chore(ci): Update the audit ci run

Cargo.lock, brane-api/Cargo.toml, brane-api/src/schema.rs
Part of the solution for #129.
=> Bumped `juniper` version to 0.16.1

.github/workflows/ci.yml, .github/workflows/mixin-cargo-check.yml, .github/workflows/mixin-cargo-test.yml, Cargo.toml, brane-api/Cargo.toml, brane-api/src/schema.rs, brane-ast/Cargo.toml, brane-cc/Cargo.toml, brane-cfg/Cargo.toml, brane-cli-c/Cargo.toml, brane-cli/Cargo.toml, brane-ctl/Cargo.toml, brane-drv/Cargo.toml, brane-dsl/Cargo.toml, brane-exe/Cargo.toml, brane-job/Cargo.toml, brane-let/Cargo.toml, brane-oas/Cargo.toml, brane-plr/Cargo.toml, brane-prx/Cargo.toml, brane-reg/Cargo.toml, brane-shr/Cargo.toml, brane-tsk/Cargo.toml, ci-cd/msrv, overview/Cargo.toml, specifications/Cargo.toml
Here are a bunch of upgrades to CI. Some mandatory because of new versions of tooling, some because they were broken or brokenish.
I think we also have to be a bit more critical of what we accept to be broken in CI. So feel free to leave more stuff unmerged and tell me to fix my stuff :innocent: 
On the other hand, CI caught some nice stuff again today, so that is good. :partying_face:
=> CI Updates

Cargo.lock, brane-ast/Cargo.toml, specifications/Cargo.toml
Dependabot keeps tripping over this update, so lets just update it
sooner so I can stop helping Dependabot every time
=> chore(deps): Update strum

.github/workflows/ci.yml, .github/workflows/mixin-cargo-llvm-cov.yml
This might take a couple of tries as debugging this stuff is a pain.
=> chore(ci): Add test coverage using codecov

Cargo.lock, brane-api/Cargo.toml, brane-cc/Cargo.toml, brane-cli-c/Cargo.toml, brane-cli/Cargo.toml, brane-ctl/Cargo.toml, brane-drv/Cargo.toml, brane-dsl/Cargo.toml, brane-exe/Cargo.toml, brane-let/Cargo.toml, brane-log/Cargo.toml, brane-plr/Cargo.toml, brane-prx/Cargo.toml, brane-reg/Cargo.toml, brane-shr/Cargo.toml, brane-tsk/Cargo.toml, specifications/Cargo.toml
Determined by cargo machete. Everything seems to still compile
@lut99 can you check this? You added them at one point. Especially the scary stuff with openssl
=> chore(deps): Remove unused dependencies

brane-api/src/main.rs
Currently the container crashes when scylla is not available immediately when the brane-api container starts.
With this PR we keep retrying while slowly increasing the time between each attempts
=> fix(api): Exponentially back off when connecting to scylla

.github/workflows/audit.yml, deny.toml
Upgrade to the most recent version, now that it is possible
=> chore(ci): Upgrade Cargo deny
